//
// Created by 12132 on 2022/1/9.
//

#ifndef BACKEND_ENGINE_SRC_RENDERER_VULKAN_VULKAN_BUFFER_H
#define BACKEND_ENGINE_SRC_RENDERER_VULKAN_VULKAN_BUFFER_H

void vulkan_create_buffer();

#endif //BACKEND_ENGINE_SRC_RENDERER_VULKAN_VULKAN_BUFFER_H
